version: '3.8'

services:
  web:
    container_name: hotel-room-booking-app-frontend
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    volumes:
      - .:/usr/src/app
      - .env:/usr/src/app/.env
    command: npm start
